branches:
  only:
    - 'master'

rvm:
  - 1.8.7
  - ree
  - 1.9.2
  - 1.9.3

env:
  global:
    - secure: "hWFKfD9snPRtilFPQAUqGijfzl8BKa05T1yhU7zdslQrzLevccQQgH4+Gzod\n7BEy6x1KZq/CIKCZq04Nd36dthc3+dlzaviA1ljclQV2Qh8Se0G0S7VYrJrn\nwO0bmSvgInaS5ybX5E23EDPahYLjnkWT7B4OGMTa9MY8maFL90A="
    - secure: "ffF6eC/SAT8MnnRGUw0N4MxZ6khthRurSeKgJZielQBylyJ55n8oBgR6Mhzb\nm6ZE+eGOM/Ww3BjV428M8QyjNvScqKxDNMw5hItCnGySpRd7J+mNgUh61Zjw\nEPhPrCfLoMolZyCOUAyiJwQCyc9OKQsYoSaKtyGWbXC6oiNgNv4="
    - TIMEOUT=1000