branches:
  only:
    - 'master'

rvm:
  - 1.8.7
  - ree
  - 1.9.2
  - 1.9.3

env:
  global:
    - secure: "vEA20Th30yv5rqlMlV9kjF8R8F1L60IWtQ6C8VsZSyQXZwazRCI5iR0Bn4F0\neGy8USa8KP72Ia8jsuWrQgsTIqmxuSKVEdo5V0QLIoQrnM4lnJFwANZml+5X\ns2ZxJ3Lfpd+oAJWir4spbYvPkGxA0HMQbIOd9W3Co7wfsZxge0g="
    - secure: "xs51S/+u10OBjjj/DOxFnTi1+0qxrou2cgfCUATTXUdgirbxgX75g31Ph0G7\nYCDKwRPoFom5MItjgkP9jk7jKK16JEawaICh87bDHDdRS7aacq9cUVOySWG1\nLHU4IeBeRABfsGERyeMDkYAI5DV78Xo8UY7rwlDYg72wiSnNefQ="
    - TIMEOUT=1000